R/sample_mallows.R, man/sample_mallows.Rd, tests/testthat/test_sample_mallows.R
Alignment of the default value of the leap_size argument to that of the compute_mallows
=> Default leap_size argument

R/misc_likelihood.R
=> Two typos removed

R/Lik_DB_MIX.R, R/expected_dist.R, inst/examples/Lik_DB_MIX_example.R, man/lik_db_mix.Rd, tests/testthat/test-Lik_DB_MIX.R, tests/testthat/test_expected_dist.R
Fixed inconsistent parameter scaling in lik_db_mix and expected_dist. Closes #60 .
=> Alpha scaling

DESCRIPTION, R/smc_get_mallows_loglik.R, R/smc_leap_and_shift_probs.R, R/smc_mallows_new_users_complete.R, R/smc_metropolis_hastings_alpha.R, R/smc_metropolis_hastings_rho.R, R/smc_post_processing_functions.R
Not 100% sure about roles. According to `?person`, the `trl` role applies to people translating from other languages into R, not the other way around; `ctr` was the closest I could find about myself. Anja added as author following apparent custom from other package contributors.
=> Added to Authors@R (solves #72)

R/smc_post_processing_functions.R
Fixes variable scope issues on a few SMC functions.
I'm adding @anjastein as a reviewer ASAP to make sure the proposed assignments are correct, but maybe @osorensen can also tell if they look proper.
=> Fixes variable scope

R/lik_db_mix.R, R/misc_likelihood.R
Deleted some redundant lines and made sure the style matches the rest of the package.
=> Edited a few lines of the likelihood functions

src/smc_calculate_forward_probability.cpp
Added lots of print statements to help with debugging
=> added print statements to calculate_forward_probability.cpp

src/smc_calculate_backward_probability.cpp
added extra print statements for debugging
=> added print statements to calculate_backwards_probability.cpp

R/smc_post_processing_functions.R, tests/testthat/test-smc_compute_rho_consensus.R
- Added @anjastein's test script for `compute_rho_consensus()`
- Minor test optimizations
- Casting df as tibble (fixes #163)
=> Convert MAP output to tibble (fixes #163)

src/RcppExports.cpp, src/misc.cpp, src/smc_calculate_backward_probability.cpp
Had some time to kill, improved some functions:
- Improved variable declaration on maybe_offset_indices() (#112)
- Improved variable declaration on calculate_backward_probability() (#112)
=> issue 112 smc memory

R/RcppExports.R, src/RcppExports.cpp, src/smc_calculate_forward_probability.cpp, src/smc_correction_kernel.cpp, src/smc_correction_kernel_pseudo.cpp, src/smc_get_mallows_loglik.cpp, src/smc_get_sample_probabilities.cpp, src/smc_leap_and_shift_probs.cpp, src/smc_mallows_new_item_rank.cpp, src/smc_mallows_new_item_rank_alpha_fixed.cpp, src/smc_mallows_new_users_complete.cpp, src/smc_mallows_new_users_partial.cpp, src/smc_mallows_new_users_partial_alpha_fixed.cpp, src/smc_metropolis_hastings_alpha.cpp, src/smc_metropolis_hastings_aug_ranking.cpp, src/smc_metropolis_hastings_aug_ranking_pseudo.cpp, src/smc_metropolis_hastings_rho.cpp
Some minor changes to finish up my work day. This takes care of another 2/4 of the tasks on issue #112, leaving just one last checkbox to close the issue.
Summary of changes:
- Declared constants and references on SMC (#112)
- Removed trailing blank line (the CI linter was complaining)
=> Declared constants and references (#112)

DESCRIPTION, R/compute_consensus.R, R/smc_post_processing_functions.R
I was able to reproduce #178 by installing R-4.0.5 on my Mac. This fixes it, and ran file on R-4.1.3 as well.
=> fixed problem on R4.0.5 on mac os

DESCRIPTION, R/compute_consensus.R, R/smc_post_processing_functions.R
* fixed problem on R4.0.5 on mac os
* small code change for readability
Since this is a bug fix, I suggest we put it in the master branch now. Will with submitting the update to CRAN at least until we see that all the C++ tests have been run for version 1.1.1 on CRAN, and that there are no issues with that.
=> fixed problem on R4.0.5 on mac os (#179)

DESCRIPTION, NEWS.md, src/misc.cpp, src/misc.h, src/smc_calculate_backward_probability.cpp, src/smc_calculate_forward_probability.cpp, src/smc_correction_kernel_pseudo.cpp, src/smc_get_mallows_loglik.cpp, src/smc_get_sample_probabilities.cpp, src/smc_mallows_new_item_rank.cpp, src/smc_mallows_new_item_rank_alpha_fixed.cpp, src/smc_mallows_new_users_complete.cpp, src/smc_mallows_new_users_partial.cpp, src/smc_mallows_new_users_partial_alpha_fixed.cpp
Starting work on issues #197 and #199.
- Replaced all arma::*word (#199)
- Increment version number to 1.1.2.9001
Edit: also changed `*vec` on misc.h because it was right _there_...
=> Replaced all arma::*word

src/distances.cpp, src/importance_sampling.cpp, src/leapandshift.cpp, src/misc.cpp, src/missing_data.cpp, src/mixtures.cpp, src/pairwise_comparisons.cpp, src/parameterupdates.cpp, src/partitionfuns.cpp, src/rmallows.cpp, src/run_mcmc.cpp, src/smc_calculate_backward_probability.cpp, src/smc_calculate_forward_probability.cpp, src/smc_correction_kernel.cpp, src/smc_correction_kernel_pseudo.cpp, src/smc_get_sample_probabilities.cpp, src/smc_leap_and_shift_probs.cpp, src/smc_mallows_new_item_rank.cpp, src/smc_mallows_new_item_rank_alpha_fixed.cpp, src/smc_mallows_new_users_complete.cpp, src/smc_mallows_new_users_partial.cpp, src/smc_mallows_new_users_partial_alpha_fixed.cpp, src/smc_metropolis_hastings_alpha.cpp, src/smc_metropolis_hastings_aug_ranking.cpp, src/smc_metropolis_hastings_aug_ranking_pseudo.cpp, src/smc_metropolis_hastings_rho.cpp
This builds further upon #203 and #204, with the aim of solving #201.
=> Removal of arma:: qualifier from functions

src/distances.cpp, src/importance_sampling.cpp, src/leapandshift.cpp, src/misc.cpp, src/missing_data.cpp, src/mixtures.cpp, src/pairwise_comparisons.cpp, src/parameterupdates.cpp, src/partitionfuns.cpp, src/rmallows.cpp, src/run_mcmc.cpp, src/smc_calculate_backward_probability.cpp, src/smc_calculate_forward_probability.cpp, src/smc_correction_kernel.cpp, src/smc_correction_kernel_pseudo.cpp, src/smc_get_sample_probabilities.cpp, src/smc_leap_and_shift_probs.cpp, src/smc_mallows_new_item_rank.cpp, src/smc_mallows_new_item_rank_alpha_fixed.cpp, src/smc_mallows_new_users_complete.cpp, src/smc_mallows_new_users_partial.cpp, src/smc_mallows_new_users_partial_alpha_fixed.cpp, src/smc_metropolis_hastings_alpha.cpp, src/smc_metropolis_hastings_aug_ranking.cpp, src/smc_metropolis_hastings_aug_ranking_pseudo.cpp, src/smc_metropolis_hastings_rho.cpp
This reverts commit 3ec2432e218b8f35dccdbe55197229573c97241a.
=> Revert "Removal of arma:: qualifier from functions (#205)"

src/leapandshift.cpp, src/missing_data.cpp, src/mixtures.cpp, src/pairwise_comparisons.cpp, src/parameterupdates.cpp, src/smc_leap_and_shift_probs.cpp, src/smc_metropolis_hastings_alpha.cpp, src/smc_metropolis_hastings_rho.cpp
Trying to familiarize myself with the code, and found some small things that could be simplified.
=> Small code modifications

R/all_topological_sorts.R, R/generate_initial_ranking.R, tests/testthat/test-generate_ranking.R
Main feature is that the recursion in all_topological_sorts() now writes directly to variables in an environment, rather than printing.
=> some improvements of the all_topological_sorts function

.github/workflows/linter.yml, DESCRIPTION, NEWS.md, R/misc.R, codecov.yml, inst/examples/sample_mallows_example.R, man/sample_mallows.Rd, tests/testthat/test-distance_function.R, tests/testthat/test-partition_function.R
This should solve #260.
Note that it is still possible to use any number of items with the Ulam distance, but one then needs to estimate the partition function using importance sampling. As noted in #260, this should have no practical consequences, because if someone ever asked for >95 items with the Ulam distance, R would likely hang for a very long time.
=> Permallows issue 260

.github/workflows/linter.yml, .github/workflows/test-coverage.yaml, R/all_topological_sorts.R, R/get_mallows_loglik.R, R/smc_mallows_deprecated.R, tests/testthat/test-assess_convergence.R, tests/testthat/test-compute_mallows.R, tests/testthat/test-get_mallows_loglik.R, tests/testthat/test-smc_individual_functions.R, tests/testthat/test-smc_mallows_new_item_rank.R, vignettes/SMC-Mallows.Rmd
Some small changes aiming to fix the linter and test-coverage checks:
- Updated linter CI (#270)
- Removed some style rules
- Fixed linting on functions and tests
- Minor rewording of SMC vignette
- Updated test CI (#270)
=> Updated CI YAMLs, fixed lints

.github/workflows/pkgdown.yaml, DESCRIPTION, NEWS.md
- @wleoncio did not show up among authors on the website, so I put him second in the list.
- Added website URL to DESCRIPTION.
- Mentioned website in NEWS.md.
=> Small changes

.github/workflows/R-CMD-check.yaml, DESCRIPTION, NEWS.md, R/RcppExports.R, R/sample_mallows.R, man/rmallows.Rd, src/RcppExports.cpp, src/rmallows.cpp
=> Removing unused argument

DESCRIPTION, NEWS.md, R/setup_rank_data.R, cran-comments.md, man/setup_rank_data.Rd, src/augmentation_class.cpp, src/clustering_class.cpp, src/data_class.cpp, src/distances.cpp, src/distances.h, src/leapandshift.cpp, src/missing_data_functions.cpp, src/proposal_functions.cpp, src/rmallows.cpp, src/smc_augmentation_class.cpp, tests/testthat/test-compute_mallows.R, tests/testthat/test-smc_update_correctness.R, tests/testthat/test-update_mallows.R, work-docs/docker-pkgs.R, work-docs/docker.sh
Solves #353, where the details are described.
This line contains the key change:
https://github.com/ocbe-uio/BayesMallows/blob/fdfa83b3eb9a21e1a68ebbf28ed084330655205d/src/data_class.cpp#L29
I wanted to make it possible to sample from the prior by providing a matrix with no rows, but that turned out to be too simple.
=> Fix CRAN issues

R/compute_mallows.R, R/validation_functions.R, cran-comments.md, src/classes.h, src/clustering_class.cpp, tests/testthat/test-assign_cluster.R, tests/testthat/test-compute_posterior_intervals.R, work-docs/docker.sh
Ref #353. 
Reproduced valgrind error on Docker image and then fixed.
=> Valgrind issue 353

R/setup_rank_data.R, R/smc_misc.R, R/tidy_mcmc.R, tests/testthat/test-compute_consensus.R, tests/testthat/test-smc_update_correctness.R
=> Take care of item names properly

DESCRIPTION, NEWS.md, R/compute_mallows_sequentially.R, cran-comments.md, inst/examples/compute_mallows_sequentially_example.R, man/compute_mallows_sequentially.Rd, tests/testthat/test-compute_mallows_sequentially.R, work-docs/docker.sh
I have to learn to run gcc-UBSAN on Docker every time I submit to CRAN. This time I only ran valgrind, but that was not enough.
=> Solving CRAN issue

BayesMallows.Rproj, DESCRIPTION, NEWS.md, R/tidy_mcmc.R, tests/testthat/test-assign_cluster.R
This should solve #423. I also added unit tests for the behavior.
=> fixed cluster thinning bug

.github/workflows/test-coverage.yaml, README.Rmd
This should close #427. Not sure whether to base the merge on `master` or `develop`, but I chose the former.
The fix involved regenerating the YAML using `usethis::use_github_actions()`, making some _ad-hoc_ adjustments, and generating an organization-wide GitHub secret [token for Codecov](https://docs.codecov.com/docs/adding-the-codecov-token).
=> Fixed test CI

DESCRIPTION, NEWS.md, R/heat_plot.R, inst/examples/heat_plot_example.R, man/heat_plot.Rd, tests/testthat/test-heat_plot.R
=> Heatplot for clusters
